More informative logging for --dev-branch

diff --git a/src/autogluon/bench/cloud/aws/docker/Dockerfile b/src/autogluon/bench/cloud/aws/docker/Dockerfile
--- a/src/autogluon/bench/cloud/aws/docker/Dockerfile
+++ b/src/autogluon/bench/cloud/aws/docker/Dockerfile
@@ -11,7 +11,7 @@ RUN apt-get update && apt-get install -y cron unzip curl \
     && mkdir -p /var/spool/cron/crontabs \
     && touch /var/log/cron.log \
     && curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
-    && unzip awscliv2.zip \
+    && unzip -q awscliv2.zip \
     && ./aws/install \
     && rm awscliv2.zip
 
@@ -23,8 +23,12 @@ RUN if [ -n "$AG_BENCH_DEV_URL" ]; then \
         && git clone --branch "$AG_BENCH_DEV_BRANCH" --single-branch "$AG_BENCH_DEV_REPO" /app/autogluon-bench \
         && pip install -e /app/autogluon-bench; \
     else \
-        echo "Installing autogluon.bench==$AG_BENCH_VERSION" \
-        && pip install autogluon.bench==$AG_BENCH_VERSION; \
+        output=$(pip install autogluon.bench==$AG_BENCH_VERSION 2>&1) || true; \
+        if echo $output | grep -q "No matching distribution"; then \
+            echo -e "ERROR: No matching distribution found for autogluon.bench==$AG_BENCH_VERSION\n\
+            To resolve the issue, try 'agbench run <config_file> --dev-branch <autogluon_bench_fork_uri>#<git_branch>'"; \
+            exit 1; \
+        fi; \
     fi
 
 RUN chmod +x entrypoint.sh /app/gpu_utilization.sh \
